version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - feedback-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - feedback-net

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: feedback_user
      POSTGRES_PASSWORD: feedback_password
      POSTGRES_DB: feedback_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - feedback-net

networks:
  feedback-net:

volumes:
  db_data:
